language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - BUILD="compat" MAKE=false SAUCELABS=false
    - SAUCE_USERNAME="jdalton"
    - secure: "woILQltl1pI3DgadZ5NrcqntdPvnRmQBwIVNZL91Ht5d9snIhgyAixI6xNAS8F8BzD9RzqzVPHay5sHfn+GhNaojcaiHs1nXAbdyclevMyfP+3MQ1HGfMSU0bv1GdT35LJ+C0u4Y3SuuZSbBlNEeLXRPMngPZahf4xL8RsZz/is="
  matrix:
    - LOADER="curl"
    - LOADER="dojo"
    - LOADER="requirejs"
    - BUILD="modern" LOADER="curl"
    - BUILD="modern" LOADER="dojo"
    - BUILD="modern" LOADER="requirejs"
    - BUILD="legacy" LOADER="curl"
    - BUILD="legacy" LOADER="dojo"
    - BUILD="legacy" LOADER="requirejs"
    - BUILD="mobile" LOADER="curl"
    - BUILD="mobile" LOADER="dojo"
    - BUILD="mobile" LOADER="requirejs"
    - SAUCELABS=true LOADER="curl"
    - SAUCELABS=true LOADER="dojo"
    - SAUCELABS=true LOADER="requirejs"
    - SAUCELABS=true BUILD="modern" LOADER="curl"
    - SAUCELABS=true BUILD="modern" LOADER="dojo"
    - SAUCELABS=true BUILD="modern" LOADER="requirejs"
    - SAUCELABS=true BUILD="legacy" LOADER="curl"
    - SAUCELABS=true BUILD="legacy" LOADER="dojo"
    - SAUCELABS=true BUILD="legacy" LOADER="requirejs"
    - SAUCELABS=true BUILD="mobile" LOADER="curl"
    - SAUCELABS=true BUILD="mobile" LOADER="dojo"
    - SAUCELABS=true BUILD="mobile" LOADER="requirejs"
matrix:
  include:
    - node_js: "0.10"
      env: SAUCELABS=true
git:
  depth: 10
branches:
  only:
    - master
before_install:
    - "[ $SAUCELABS != false ] && npm i ecstatic request sauce-tunnel || true"
before_script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
script:
  - "[ $BUILD != 'compat' ] && [ $BUILD != 'modern' ] && MAKE=true || true"
  - "[ $MAKE != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize $BUILD exports=amd -o ./$BUILD || true"
  - "[ $SAUCELABS != false ] && true || phantomjs ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\""
  - "[ $SAUCELABS == false ] && true || node ./node_modules/lodash/test/saucelabs.js \"/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\""
  - "[ $SAUCELABS == false ] && [ $BUILD != 'mobile' ] && [ $BUILD != 'modern' ] && true || node ./node_modules/lodash/test/saucelabs.js \"/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER&compat=7\""
