language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  global:
    - BUILD="compat" MAKE=false
  matrix:
    - LOADER="curl"
    - LOADER="dojo"
    - LOADER="requirejs"
    - BUILD="modern" LOADER="curl"
    - BUILD="modern" LOADER="dojo"
    - BUILD="modern" LOADER="requirejs"
    - BUILD="legacy" LOADER="curl"      MAKE=true
    - BUILD="legacy" LOADER="dojo"      MAKE=true
    - BUILD="legacy" LOADER="requirejs" MAKE=true
    - BUILD="mobile" LOADER="curl"      MAKE=true
    - BUILD="mobile" LOADER="dojo"      MAKE=true
    - BUILD="mobile" LOADER="requirejs" MAKE=true
git:
  depth: 1
branches:
  only:
    - master
before_script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
script:
  - "[ $MAKE != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=amd -o ./$BUILD || true"
  - "phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/main.js&loader=$LOADER"
